services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres-16
    environment:
      POSTGRES_DB: vrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password44!
      TZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    restart: always
    container_name: mailpit
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  db:
